// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface ProfileLayoutSocialIconsV1Block {
  _type: "social_icons";
  _version: 1;
  _key: string;
  "links"?: { "network": "website" | "email" | "phone" | "x" | "instagram" | "youtube" | "tiktok" | "linkedin" | "github" | "gitlab" | "facebook" | "threads" | "bluesky" | "mastodon" | "discord" | "twitch" | "telegram" | "whatsapp" | "pinterest" | "snapchat" | "reddit" | "spotify" | "applemusic" | "soundcloud" | "bandcamp" | "vimeo" | "medium" | "substack" | "patreon" | "kofi" | "buymeacoffee" | "dribbble" | "behance" | "codepen" | "rss"; "url": string }[] | null;
}

export type ProfileLayoutSocialIconsBlock = ProfileLayoutSocialIconsV1Block;

export interface ProfileLayoutLinkV1Block {
  _type: "link";
  _version: 1;
  _key: string;
  "title": string;
  "url": string;
  "description"?: string | null;
  "icon"?: "website" | "email" | "phone" | "link" | "x" | "instagram" | "youtube" | "tiktok" | "linkedin" | "github" | "gitlab" | "facebook" | "threads" | "bluesky" | "mastodon" | "discord" | "twitch" | "telegram" | "whatsapp" | "pinterest" | "snapchat" | "reddit" | "spotify" | "applemusic" | "soundcloud" | "bandcamp" | "vimeo" | "medium" | "substack" | "patreon" | "kofi" | "buymeacoffee" | "dribbble" | "behance" | "codepen" | "rss" | null;
  "thumbnail"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "featured"?: boolean | null;
  "new_tab"?: boolean | null;
}

export type ProfileLayoutLinkBlock = ProfileLayoutLinkV1Block;

export interface ProfileLayoutLinkListV1Block {
  _type: "link_list";
  _version: 1;
  _key: string;
  "links"?: { "label": string; "url": string; "icon"?: "website" | "email" | "phone" | "link" | "x" | "instagram" | "youtube" | "tiktok" | "linkedin" | "github" | "gitlab" | "facebook" | "threads" | "bluesky" | "mastodon" | "discord" | "twitch" | "telegram" | "whatsapp" | "pinterest" | "snapchat" | "reddit" | "spotify" | "applemusic" | "soundcloud" | "bandcamp" | "vimeo" | "medium" | "substack" | "patreon" | "kofi" | "buymeacoffee" | "dribbble" | "behance" | "codepen" | "rss" | null }[] | null;
}

export type ProfileLayoutLinkListBlock = ProfileLayoutLinkListV1Block;

export interface ProfileLayoutHeadingV1Block {
  _type: "heading";
  _version: 1;
  _key: string;
  "title": string;
  "subtitle"?: string | null;
}

export type ProfileLayoutHeadingBlock = ProfileLayoutHeadingV1Block;

export interface ProfileLayoutProjectV1Block {
  _type: "project";
  _version: 1;
  _key: string;
  "title": string;
  "description"?: string | null;
  "url"?: string | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "tag"?: string | null;
}

export type ProfileLayoutProjectBlock = ProfileLayoutProjectV1Block;

export interface ProfileLayoutTextV1Block {
  _type: "text";
  _version: 1;
  _key: string;
  "content"?: PortableTextBlock[] | null;
}

export type ProfileLayoutTextBlock = ProfileLayoutTextV1Block;

export interface ProfileLayoutImageV1Block {
  _type: "image";
  _version: 1;
  _key: string;
  "image": { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  "caption"?: string | null;
  "link"?: string | null;
}

export type ProfileLayoutImageBlock = ProfileLayoutImageV1Block;

export interface ProfileLayoutEmbedV1Block {
  _type: "embed";
  _version: 1;
  _key: string;
  "url": string;
  "caption"?: string | null;
}

export type ProfileLayoutEmbedBlock = ProfileLayoutEmbedV1Block;

export interface ProfileLayoutDividerV1Block {
  _type: "divider";
  _version: 1;
  _key: string;
  "style"?: "line" | "dots" | "space" | null;
}

export type ProfileLayoutDividerBlock = ProfileLayoutDividerV1Block;

export type ProfileLayoutBlock = ProfileLayoutSocialIconsBlock | ProfileLayoutLinkBlock | ProfileLayoutLinkListBlock | ProfileLayoutHeadingBlock | ProfileLayoutProjectBlock | ProfileLayoutTextBlock | ProfileLayoutImageBlock | ProfileLayoutEmbedBlock | ProfileLayoutDividerBlock;

export interface Profile {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  bio?: string;
  avatar?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  location?: string;
  layout?: ProfileLayoutBlock[];
  theme_mode?: "system" | "light" | "dark";
  color_scheme?: "violet" | "ocean" | "sunset" | "forest" | "rose" | "amber" | "candy" | "cyber" | "mono" | "slate";
  accent_color?: string;
  bg_style?: "gradient" | "color" | "image";
  bg_color?: string;
  bg_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  text_color?: string;
  card_color?: string;
  card_style?: "soft" | "outline" | "solid" | "glass";
  corner_radius?: "rounded" | "pill" | "sharp";
  avatar_shape?: "circle" | "rounded" | "square";
  font?: "modern" | "classic" | "mono" | "rounded";
  footer_branding?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    profiles: Profile;
  }
}